# -*- coding: utf-8 -*-
"""bobble sort

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o16pSQ3RaIPYByHseRs-mi3nUcDrzzZC
"""

def bubble(arr):
    n = len(arr)
    for i in range(n-1):
        for j in range(0, n-i-1):
            if arr[j] > arr[j +1]:
                arr[j] , arr[j+1] = arr[j+1], arr[j]
    return arr

arr = ["Rahul", "Amith", "Sneha", "Priya","Kiran"]
sorted = bubble(arr)
print("sorted array:", sorted)